### PR TITLE
[SHOT-3610] updated import builtins for v2020.x VRED versions

### PR DESCRIPTION
**Pull request by rob-aitchison**

### CODE REVIEW

**Review by staceyoue — DISMISSED** [review]
LGTM!

**Comment by rob-aitchison** [comment]
Discovered errors, in Draft mode now.

**Comment by rob-aitchison** [comment]
Hi @staceyoue just discovered different API functionality per VRED 2020.x making it more elaborate. Ready for review and testing now. Thanks!

**Review by staceyoue — APPROVED** [review]
Looks good!

**Pull request merged**
