### PR TITLE
[SHOT-3506] Clean the engine

### PR DESCRIPTION
**Pull request by staceyoue**
* Remove static method get_vred_main_window() and instead use _get_dialog_parent().
* Rename _get_dialog_parent() to get_dialog_parent() to remove protected method convention, since get_dialog_parent() is now used outside of the engine class.

### CODE REVIEW

**Comment by staceyoue** [comment]
@barbara-darkshot ah good catch, I missed that it was overriding tk-core engine method. If that's the case then, and `_get_dialog_parent()` has a protected method convention, should we not be accessing that method from outside the class in `menu.py`? And we should actually keep the static method for that purpose?

**Comment by barbara-darkshot** [comment]
hum, do we really need the static method even after refactoring the way the SG menu is built because it seems this is the only place it's used, right?
for me it could be confusing for the users to have a documented protected method and a non-documented static method: which one to use? :)

**Comment by staceyoue** [comment]
I was just wondering how strict you are with the protected method convention -- I'm used to more of the C++/C# style where you are prohibited from using protected methods outside the parent or child class. So I'm good with either change, and I'll defer to your judgement 👍

**Review by barbara-darkshot — APPROVED** [review]
LGTM!

**Pull request merged**
