### PR TITLE
SHOT-3618: Ensure that the engine reloads and restarts properly

### PR DESCRIPTION
**Pull request by staceyoue**

### CODE REVIEW

**Review by rob-aitchison — DISMISSED** [review]
Looks good!

**Review by barbara-darkshot — APPROVED** [review]
LGTM!

**Comment by staceyoue** [comment]
@rob-aitchison requested review since merging conflicts with master made your review stale -- there should be no change from when you last approved it

**Review by rob-aitchison — APPROVED** [review]
👍

**Pull request merged**
