### PR TITLE
Support Qt6/PySide6

### PR DESCRIPTION
**Pull request by staceyoue**
Minimal code changes in tk-vred, since tk-core will take care of patching Qt6 to Qt4 as the first step in support Qt6/PySide6 for VRED

### CODE REVIEW

**Review by rob-aitchison — DISMISSED** [review]
Looks great, thank you!

**Review by rob-aitchison — APPROVED** [review]
Just re-reviewed the commit after my approval to be aware of it - approved again and thanks again!

**Comment by rob-aitchison** [comment]
@barbara-darkshot , as discussed earlier as well - thanks!

**Review by barbara-darkshot — APPROVED** [review]
LGTM!

**Pull request merged**
